version: 2
updates:
  # NuGet config for 'SmallsOnline.VSCode.Configurator'
  - package-ecosystem: "nuget"
    directory: "/src/Configurator"
    target-branch: "main"
    labels:
      - "Configurator"
    schedule:
      interval: "daily"
    assignees:
      - "Smalls1652"

  # GitHub Actions config for the repo
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    assignees:
      - "Smalls1652"